// Copyright (C) 2015 The Gravitee team (http://gravitee.io)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//         http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"bytes"
	"fmt"
	"os"
	"strings"

	"gopkg.in/yaml.v3"
)

type overlay struct {
	Overlay string      `yaml:"overlay"`
	Info    yaml.Node   `yaml:"info"`
	Actions []yaml.Node `yaml:"actions"`
}

func main() {
	if len(os.Args) < 4 {
		fmt.Fprintln(os.Stderr, "usage: mergeoverlay in1.yaml [in2.yaml ...] out.yaml")
		os.Exit(1)
	}
	inPaths, outPath := os.Args[1:len(os.Args)-1], os.Args[len(os.Args)-1]
	merged := overlay{Info: mergedInfo()}
	for i, path := range inPaths {
		raw, err := os.ReadFile(path)
		if err != nil {
			fatal(err)
		}
		var next overlay
		if err := yaml.Unmarshal(raw, &next); err != nil {
			fatal(fmt.Errorf("%s: %w", path, err))
		}
		if i == 0 {
			merged.Overlay = next.Overlay
		}
		markSource(next, path)
		merged.Actions = append(merged.Actions, next.Actions...)
	}
	var out bytes.Buffer
	out.WriteString("# Code generated by mergeoverlay.go from " + strings.Join(inPaths, ", ") + ". DO NOT EDIT.\n\n")
	enc := yaml.NewEncoder(&out)
	enc.SetIndent(2)
	if err := enc.Encode(&merged); err != nil {
		fatal(err)
	}
	if err := os.WriteFile(outPath, out.Bytes(), 0o644); err != nil {
		fatal(err)
	}
}

func mergedInfo() yaml.Node {
	var info yaml.Node
	if err := info.Encode(map[string]string{"title": "Merged overlay", "version": "0.0.1"}); err != nil {
		fatal(err)
	}
	return info
}

// markSource heads the first action of an overlay with a banner naming its file and title,
// so the merged output reads as one section per source overlay.
func markSource(o overlay, path string) {
	if len(o.Actions) == 0 {
		return
	}
	var info struct {
		Title string `yaml:"title"`
	}
	if err := o.Info.Decode(&info); err != nil {
		fatal(fmt.Errorf("%s: %w", path, err))
	}
	first := &o.Actions[0]
	banner := fmt.Sprintf("\n# ---------------------------------------------------------------------------\n# %s\n# %s\n# ---------------------------------------------------------------------------", path, info.Title)
	first.HeadComment = strings.TrimSpace(banner + "\n" + first.HeadComment)
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
