// Copyright (C) 2015 The Gravitee team (http://gravitee.io)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//         http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// mergespec merges several OpenAPI documents into one: paths, components and tags are
// unioned, everything else (info, servers, security) comes from the first document.
// A path, component or operationId defined twice is an error, so a fragment can never
// silently override the host document.
package main

import (
	"bytes"
	"fmt"
	"os"
	"strings"

	"gopkg.in/yaml.v3"
)

func main() {
	if len(os.Args) < 4 {
		fmt.Fprintln(os.Stderr, "usage: mergespec in1.yaml [in2.yaml ...] out.yaml")
		os.Exit(1)
	}
	inPaths, outPath := os.Args[1:len(os.Args)-1], os.Args[len(os.Args)-1]

	base := load(inPaths[0])
	for _, path := range inPaths[1:] {
		if err := merge(base, load(path)); err != nil {
			fatal(fmt.Errorf("%s: %w", path, err))
		}
	}
	if err := checkOperationIds(base); err != nil {
		fatal(err)
	}

	var out bytes.Buffer
	out.WriteString("# Code generated by mergespec from " + strings.Join(inPaths, ", ") + ". DO NOT EDIT.\n\n")
	enc := yaml.NewEncoder(&out)
	enc.SetIndent(2)
	if err := enc.Encode(base); err != nil {
		fatal(err)
	}
	if err := os.WriteFile(outPath, out.Bytes(), 0o644); err != nil {
		fatal(err)
	}
}

// load reads a YAML document and returns its root mapping node.
func load(path string) *yaml.Node {
	raw, err := os.ReadFile(path)
	if err != nil {
		fatal(err)
	}
	var doc yaml.Node
	if err := yaml.Unmarshal(raw, &doc); err != nil {
		fatal(fmt.Errorf("%s: %w", path, err))
	}
	if doc.Kind != yaml.DocumentNode || len(doc.Content) != 1 || doc.Content[0].Kind != yaml.MappingNode {
		fatal(fmt.Errorf("%s: not a YAML mapping document", path))
	}
	return doc.Content[0]
}

// merge adds the paths, components and tags of next to base.
func merge(base, next *yaml.Node) error {
	if err := mergeMapping(base, next, "paths"); err != nil {
		return err
	}
	baseComponents, nextComponents := ensureMapping(base, "components"), mapping(next, "components")
	if nextComponents != nil {
		for i := 0; i < len(nextComponents.Content); i += 2 {
			section := nextComponents.Content[i].Value
			if err := mergeMapping(baseComponents, nextComponents, section); err != nil {
				return fmt.Errorf("components.%s", err)
			}
		}
	}
	mergeTags(base, next)
	return nil
}

// mergeMapping copies every entry of next[key] into base[key], refusing duplicates.
func mergeMapping(base, next *yaml.Node, key string) error {
	from := mapping(next, key)
	if from == nil {
		return nil
	}
	to := ensureMapping(base, key)
	for i := 0; i < len(from.Content); i += 2 {
		k := from.Content[i].Value
		if lookup(to, k) != nil {
			return fmt.Errorf("%s: %q is defined in more than one document", key, k)
		}
		to.Content = append(to.Content, from.Content[i], from.Content[i+1])
	}
	return nil
}

// mergeTags appends the tags of next that base does not declare yet, by name.
func mergeTags(base, next *yaml.Node) {
	from := lookup(next, "tags")
	if from == nil || from.Kind != yaml.SequenceNode {
		return
	}
	to := lookup(base, "tags")
	if to == nil {
		to = &yaml.Node{Kind: yaml.SequenceNode, Tag: "!!seq"}
		base.Content = append(base.Content, scalar("tags"), to)
	}
	for _, tag := range from.Content {
		name := lookup(tag, "name")
		if name == nil || findTag(to, name.Value) == nil {
			to.Content = append(to.Content, tag)
		}
	}
}

func findTag(tags *yaml.Node, name string) *yaml.Node {
	for _, tag := range tags.Content {
		if n := lookup(tag, "name"); n != nil && n.Value == name {
			return tag
		}
	}
	return nil
}

// checkOperationIds fails when two operations share an operationId: codegen would
// otherwise emit two methods with the same name.
func checkOperationIds(root *yaml.Node) error {
	seen := map[string]string{}
	paths := mapping(root, "paths")
	if paths == nil {
		return nil
	}
	for i := 0; i < len(paths.Content); i += 2 {
		path, item := paths.Content[i].Value, paths.Content[i+1]
		for j := 0; j+1 < len(item.Content); j += 2 {
			op := item.Content[j+1]
			id := lookup(op, "operationId")
			if id == nil {
				continue
			}
			where := paths.Content[i].Value + "." + item.Content[j].Value
			if prev, dup := seen[id.Value]; dup {
				return fmt.Errorf("operationId %q is used by %s and %s", id.Value, prev, where)
			}
			seen[id.Value] = where
			_ = path
		}
	}
	return nil
}

// lookup returns the value node for key in a mapping node, or nil.
func lookup(m *yaml.Node, key string) *yaml.Node {
	if m == nil || m.Kind != yaml.MappingNode {
		return nil
	}
	for i := 0; i+1 < len(m.Content); i += 2 {
		if m.Content[i].Value == key {
			return m.Content[i+1]
		}
	}
	return nil
}

// mapping returns m[key] when it is a mapping node, or nil.
func mapping(m *yaml.Node, key string) *yaml.Node {
	v := lookup(m, key)
	if v == nil || v.Kind != yaml.MappingNode {
		return nil
	}
	return v
}

// ensureMapping returns m[key], creating an empty mapping when absent.
func ensureMapping(m *yaml.Node, key string) *yaml.Node {
	if v := mapping(m, key); v != nil {
		return v
	}
	v := &yaml.Node{Kind: yaml.MappingNode, Tag: "!!map"}
	m.Content = append(m.Content, scalar(key), v)
	return v
}

func scalar(v string) *yaml.Node {
	return &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: v}
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
